site_name: Domible Documentation
site_url: https://joeldodson.github.io/domible
repo_url: https://github.com/joeldodson/domible
repo_name: Domible on GitHub
site_description: set of python classes used to generate accessible HTML, JavaScript, and CSS
site_author: Joel Dodson

nav:
  - Home: index.md
  - Change Log: CHANGELOG.md
  - Contributing: CONTRIBUTING.md
  - Code of Condut: CONDUCT.md

theme:
  name: material 
